### ISSUE TITLE
Adding support for USB soundcards?

### ISSUE THREAD

**Issue by jeloneal** [dwhinham/mt32-pi#10]
Especially on old retro computers it would be nice to be able to mix midi output (music) with digital output (sound effect and speech). Therefore I'm trying to attach an USB soundcard with line-in and out. 

The idea is to input digital audio in line-in and mix that with the midi sound to put both together out through the line-out.

Do you think that is possible? 

It would also allow for a bit better output quality for music compared to default RPi PWM.

**Comment by dwhinham** [comment]
Unfortunately USB audio support won't be possible without a lot of work on Circle (the baremetal framework we depend on), as it doesn't have any drivers or support in the USB stack for this kind of device. If this changes in the future, we can add it.

For better quality audio, I am focusing on I2S DAC support such as HiFiBerry, IQaudIO, JustBoom, Pi-Fi, and the many other Raspberry Pi DAC HATs that are available.

As for mixing audio from the vintage PC, it would be best to pick up a stereo mixer - have a look on Amazon or AliExpress for "mini stereo mixer", you can get these quite cheaply.
