### ISSUE TITLE
Low Voltage error

### ISSUE THREAD

**Issue by ReadyPlayer29** [dwhinham/mt32-pi#101]
Updated firmware and everytime i power on i get a low voltage error on mt32 pi display.

Never happened before with 0.85 so have had to revert back to that

**Comment by ReadyPlayer29** [comment]
Maybe it's something to do with the user port on a mister update??

**Comment by dwhinham** [comment]
Please read this section of the wiki re: low voltage warnings and MiSTer: https://github.com/dwhinham/mt32-pi/wiki/MiSTer-FPGA-user-port-connection#low-voltage-warnings

This is not a bug and it'll just be a coincidence if it didn't happen with older versions.
