### ISSUE TITLE
Pi1B and Zero

### ISSUE THREAD

**Issue by TheElf01** [dwhinham/mt32-pi#120]
Hi, great project! thanks,  is working perfect in Pi2 and 3 i tested

I have some Pi1B and Zero, i was thinking to test soundfont, no munt,   but i think maybe the kernel is not working?  is only compiled for 2 and 3?

thanks!

**Comment by dwhinham** [comment]
Hi,

Thanks for appreciating the project!
Regarding Pi 0/1, this question is answered in the [FAQ](https://github.com/dwhinham/mt32-pi/wiki/FAQ#q-which-models-of-raspberry-pi-are-supported-and-if-not-why-not).
