### ISSUE TITLE
Feature Request: Add OPL3 hardware support (re: RetroWave OPL3)

### ISSUE THREAD

**Issue by sofakng** [dwhinham/mt32-pi#130]
I've just discovered the [RetroWave OPL3 Sound Card](https://www.tindie.com/products/sudomaker/retrowave-opl3-sound-card/) which is basically a real Yamaha YMF262 on a small PCB that connects to a Raspberry Pi.

Would it be possible to merge these projects and create a single card/addon that supports baremetal MT32 and OPL3?

**Comment by dwhinham** [comment]
Possible? Yes
Likely? No

What exactly would be benefits be of going to the trouble of purchasing this board and then spending a lot of effort porting its software stack and integrating it into mt32-pi when its own software solutions would probably do a better job?

It has its own independent audio output so it's not like the user gains any convenience in terms of cabling, apart from maybe MIDI input, but MIDI can be daisy-chained easily; audio has to be mixed.

PS: Please use the issue templates in future.
