### ISSUE TITLE
Possible to use USB-to-Serial adapters with mt32-pi?

### ISSUE THREAD

**Issue by sofakng** [dwhinham/mt32-pi#144]
I'm looking for the easiest way to connect an old DOS PC to an mt32-pi (without using MIDI cables or adapters).

Can I use a USB-to-serial adapter to connect the PC to the mt32-pi?

For example, this cable ([USB to RS232 Adapter with PL2303](https://www.amazon.com/Adapter-Chipset-CableCreation-Converter-Register/dp/B0769FY7R7/ref=sr_1_15?dchild=1&keywords=serial%2Bport%2Bmale%2Busb&qid=1623891215&sr=8-15&th=1) has a female DB9 connector (to plug into the DOS PC) and then a USB connector to plug into the mt32-pi.

Would this work?

**Comment by dwhinham** [comment]
> Issues are for reproducible bug reports and feature requests.
Requests for support and "how-to" questions may be closed without notice.
