### ISSUE TITLE
 🐛 [BUG] MIDI level meters can appear stuck at random levels after a while

### ISSUE THREAD

**Issue by dwhinham** [dwhinham/mt32-pi#148]
## Hardware and software

- **mt32-pi version:** v0.10.0
- **Raspberry Pi model:** Any
- **HATs:** Any
- **USB devices:** None
- **MIDI host:** Any

## Bug description

After playing some music and then allowing the Pi to idle for an extended period of time (several minutes, possibly over an hour) the MIDI level meters can suddenly appear stuck at random levels even though no notes are playing.

Sending a GM/GS reset SysEx command will un-stick the bars (e.g. with [mt32-pi-control](https://github.com/gmcn42/mt32-pi-control): `mt32-pi.exe --gs-reset`).

## Steps to reproduce

1. Play some MIDI music and then stop it.
2. Wait for a long time.
3. Notice bars have become stuck at unexpected levels.

## Expected behavior

The bars should stay zeroed.

## Additional information

Suspected integer overflow in the bar envelope calculations (1MHz timer wrapping).

**Comment by M-Walrus** [comment]
I'd like to add, that music doesn't need to stop for this to occur.

Follow these steps in Quest for Glory 1 (EGA) in a scene with non-stop music to reproduce this issue:

Start game, walk SE to exit town, and then take this path to Erana's Peace:

North 1  (Healer's Hut)
West 1  (Centaur)
North until blocked by rocks
East 1
North 1

Let the music play for a while here and the same issue will occur.

(note: only tried with MT-32, using v1 rom)
