### ISSUE TITLE
"[lcd]" section missing in mt_32.cfg for release 0.3 

### ISSUE THREAD

**Issue by jsmolina** [dwhinham/mt32-pi#17]
Hi,

I've been looking for the option to enable the MIDI pi-hat LCD, until I realised that repo had this 'sdcard' folder. It should be included on release.

Very nice job!!!

Thanks!

**Comment by dwhinham** [comment]
Thanks for reporting this!

This unintentional of course - I think the caching system in GitHub Actions (which I use to speed up the build) is overwriting the latest config with an old version.

I'll take care of this and prepare a new release very shortly. 😃

**Comment by dwhinham** [comment]
[v0.3.1](https://github.com/dwhinham/mt32-pi/releases/tag/v0.3.1) is now available with the missing config section included and some other minor fixes.

Thanks again! 😃
