### ISSUE TITLE
💡 [FEATURE] Switch ROM/Soundfont remotely via MiSTer

### ISSUE THREAD

**Issue by rpc72** [dwhinham/mt32-pi#182]
Would be nice if there was a way to switch the ROMs switch soundfonts programmatically from the MiSTer so that each game can be configured for MT-32, SC-55 or SC-88 depending on what was used to make the music in the game.  I know that a program needs to be configured on the MiSTer side to catalog the type of MIDI/soundfont per game and trigger the switch when a game is launced.

Does any of this make sense?

Thanks!

## Is your feature request related to a problem? Please describe.

_A clear and concise description of what problem(s) this feature request would solve. For example:_

I'm always frustrated when...

## Describe the solution you'd like

_A clear and concise description of what you want to happen._

## Describe alternatives you've considered

_A clear and concise description of any alternative solutions or features you've considered._

## Additional context

_Add any other context, videos, or audio recordings about the feature request here._

**Comment by dwhinham** [comment]
This feature already exists by means of [Custom SysEx Messages](https://github.com/dwhinham/mt32-pi/wiki/Custom-System-Exclusive-messages) and tools such as https://github.com/gmcn42/mt32-pi-control or the older [mpuctl](https://github.com/MiSTer-devel/ao486_MiSTer/tree/master/sw/mpuctl).

An example of this in use is with the Top300 DOS game pack by @flynnsbit - mt32-pi-control is run before each game starts to swap the synth mode.
