### ISSUE TITLE
💡 [FEATURE] Support for RPi Zero 2

### ISSUE THREAD

**Issue by sorgelig** [dwhinham/mt32-pi#208]
Should it work with current release or does it require a new release?

**Comment by dwhinham** [comment]
No, it is not supported. It will be supported in the next release,.

**Comment by sorgelig** [comment]
i want to make a "side hat" for MiSTer :) Will be a button-less and screen-less. A simple mini plug.
Ok. Will wait for your release. As i see Circle doesn't support this board yet. Hope you figure out it.
