### ISSUE TITLE
🐛 [BUG] Problem with ssd1306_i2c in pi zero 2

### ISSUE THREAD

**Issue by antmerino** [dwhinham/mt32-pi#214]
## Bug description

I use pi zero 2 with a ssd1306_i2c lcd with the compiled version in the develop branch.
When I've been playing something for about 10 minutes, the lcd starts scrolling right and up.
Attached configuration file and a video with the problem.
Thanks

## Steps to reproduce
any playback under mt32 after 10 minutes or more

## Hardware and software

- **mt32-pi version:** Branch develop
- **Raspberry Pi model:** _Raspberry pi zero 2_
- **HATs:** _mt32-pi with ssd1306_i2c _
- **USB devices:** _None_
- **MIDI host:** _Mister_

## Configuration file
[mt32-pi.cfg.txt](https://github.com/dwhinham/mt32-pi/files/7689789/mt32-pi.cfg.txt)

## Videos/audio recordings

![8181643d-84e2-4fbd-8999-29559151f50b](https://user-images.githubusercontent.com/84129844/145509674-1a3a3f6c-ca92-4190-915c-d4d4c3f83825.jpeg)

https://user-images.githubusercontent.com/84129844/145509945-a6c2e740-c6a5-492e-97c3-9e5668a326c2.mp4

**Comment by dwhinham** [comment]
From the [FAQ](https://github.com/dwhinham/mt32-pi/wiki/FAQ#q-im-using-a-mister-interface-pcb-with-a-usb-a-a-cable-and-the-oled-display-is-scrambledthe-osd-controls-dont-workaudio-is-distorted-or-missing---whats-wrong):

> **Q:** I'm using a MiSTer interface PCB with a USB A-A cable and the OLED display is scrambled/the OSD controls don't work/audio is distorted or missing - what's wrong?

> **A:** Your cable is probably too long and the I²C and/or I²S signals are being degraded. Please try a short cable as explained [in this section of the MiSTer wiki page](https://github.com/dwhinham/mt32-pi/wiki/MiSTer-FPGA-user-port-connection#-important-cabling-considerations).

**Comment by antmerino** [comment]
my cable is https://www.mycablemart.com/store/cart.php?m=product_detail&p=7270 , This's recomend in the wiki and only has 15 cm
we have tested with a raspberry 3 and with other lcd. and this works. 
Please, can you test with your pi zero 2 and this lcd?
thanks

**Comment by dwhinham** [comment]
There are no issues with the OLED driver on my Zero 2 W test setup.

You have a hardware issue. Talk to whoever sold you it.
