### ISSUE TITLE
Unreliable playing of multiple notes simultaneously?

### ISSUE THREAD

**Issue by olliraa** [dwhinham/mt32-pi#24]
Hi.

Running with the ready-assembled hat from Araranet (GPIO Midi and i2s hifi audio) :) Works ok, but for some reason I cannot play realiably more than one note at a time. If I try to play a chord with 3 notes, only one is played. But if I play the same notes individually (1-2-3) it works. Is this a config issue or something else?

Running Pi 3B+ and 0.3.1

Thanks!

**Comment by dwhinham** [comment]
Unfortunately you're experiencing issue #21. It's not a config issue and about 90% sure it's a hardware issue and not software.

Please join that thread and add details of your setup (most importantly, details of what you're connecting to the GPIO MIDI). If you have other sources to try, you should do so.

Thanks!
