### ISSUE TITLE
 🐛 [BUG] Audio playback stutters and time-drifts during FTP transfer

### ISSUE THREAD

**Issue by c0d3h4x0r** [dwhinham/mt32-pi#249]
## Hardware and software

- **mt32-pi version:** v0.10.0
- **Raspberry Pi model:** Raspberry Pi 3 Model A+
- **HATs:** MiSTer mt32-pi
- **USB devices:** None
- **MIDI host:** MiSTer USER I/O port

## Bug description

FTP file transfer noticeably taxes the performance of audio reproduction if both are happening simultaneously.

## Steps to reproduce

n/a

## Expected behavior

I realize the Pi may simply not be powerful enough to do both simultaneously.  So, why even permit that?  It should be able to boot into either FTP/admin mode or into playback/normal mode, maybe depending on whether the user is holding down one (or both?) of the buttons or not at power on or by momentarily prompting on the LCD display to "press button now to enter admin mode" during boot, so that doing both admin stuff (like FTP) and audio playback simultaneously is impossible.

Furthermore, this could open up the ability to add other convenient admin functionality (such as multi-threaded FTP server, or SSH server) without worrying about taxing the CPU or RAM too much for normal audio playback.

## Configuration file

<details>
<summary>Click to expand</summary>

n/a

</details>

## Videos/audio recordings

n/a

## Additional information

n/a

**Comment by dwhinham** [comment]
This is not a "not powerful enough" problem, but a task scheduling problem. Circle is not an OS, there is no such thing as threads, and (co-operative) multi-tasking is limited to the first CPU core.

This is going to be a "wontfix", I'm afraid. The TL;DR is that there is some stuff that all must happen on one core ("single-threaded", if you want) and there is no solution unless Circle decides it wants to become more like an operating system.

Discussions about controling/toggling FTP etc ideas are a separate topic and I already have plans for this as part of the menu system I will be implementing. I don't think it's worth blocking the user from accessing FTP while music is playing. It won't improve anything.

SSH is not really relevant to this baremetal project.
