### ISSUE TITLE
Unusual Behaviour 🐛 [BUG]

### ISSUE THREAD

**Issue by ishtangli** [dwhinham/mt32-pi#291]
## Hardware and software

- **mt32-pi version: 12.0
- **Raspberry Pi model: pi zero 2w
- **HATs: Yavimaya's zero 2w hat
- **USB devices:** _e.g. None_
- **MIDI host: Mister

## Bug description

The screen is messed up and some instruments arent playing as loud

## Steps to reproduce

_Provide clear steps to reproduce the problem. For example:_

1. Load Monkey Island 2 from MS-DOS.
2. Visit the mapmaker's room.
3. Hear distortion in audio.

## Expected behavior

_A clear and concise description of the behavior you expected._

## Configuration file

<details>
<summary>Click to expand</summary>

```ini
Paste the contents of your mt32-pi.cfg here.
```
</details>

## Videos/audio recordings

_If appropriate, add a short video or audio recording to help explain your problem._

## Additional information

Downgraded to 11.3 and the problem disappeared. Updated via update script if it matters

**Comment by dwhinham** [comment]
Fixed in v0.12.1.
