### ISSUE TITLE
 🐛 [BUG] mt32-pi / MiSTer I²C comms broken with recent Raspberry Pi firmware

### ISSUE THREAD

**Issue by dwhinham** [dwhinham/mt32-pi#292]
Issues #289 and #291 described problems with mt32-pi v0.12.0 when used with MiSTer FPGA.

The problem has been narrowed-down as being related to the Raspberry Pi firmware version used (`start_cd.elf` / `fixup_cd.dat`).

Circle Step 44.5 (as shipped in mt32-pi v0.12.0) recommends firmware from [March 24](https://github.com/raspberrypi/firmware/commit/ea4c803c57697aad951a27fcd64c01ef16f9fe7f).

With firmware versions later than [March 22](https://github.com/raspberrypi/firmware/commit/6544efc34af0ce0e15ed99fab0ec1a980413cb1f), I²C communications between mt32-pi and MiSTer are broken (corrupt OLED screen, "Unknown mode" errors, etc).

This has been temporarily worked-around in v0.12.1 by reverting to the previous recommended firmware version (January 20th).

This issue is to track investigation into what the underlying issue is. The firmware commit history suggests changes related to clocks, hence there could be an issue with how Circle's mailbox driver is retrieving clocks via the firmware (the I²C master driver appears to rely on the core clock).

**Comment by nikitalita** [comment]
I can confirm the clock is wrong when using the March 24th firmware.

With a configuration file that has i2c bus speed set to 400khz.

Mt32-pi 0.12.1 (January 20th firmware), Clock is at correct frequency of 400khz
![image](https://user-images.githubusercontent.com/69168929/173705470-bdbcb3b7-90ad-4f6a-825e-b1aff791005a.png)

Mt32-pi 0.12.0 (March 24th firmware), Clock is at an incorrect frequency of ~641khz
![image](https://user-images.githubusercontent.com/69168929/173705609-a3e88577-9f91-4a80-a094-04c86d1e6111.png)

**Comment by nikitalita** [comment]
I think this can be closed now?

**Comment by dwhinham** [comment]
Yes, it can - I was being lazy because the commit message would have closed it when it hit master 🙂
