### ISSUE TITLE
💡 [FEATURE]

### ISSUE THREAD

**Issue by tebl** [dwhinham/mt32-pi#302]
I love using the device, but some of the sound fonts I've got on there have very non-descriptive names and so I'm having trouble remembering them. Would it be possible to have a file where I can set a different description to be used when stepping through and loading them? Alternatively designate them as profiles, selecting mode and then the specified ROM.

**Comment by dwhinham** [comment]
You can easily edit the names using a SoundFont editor like [Polyphone](https://www.polyphone-soundfonts.com/download); pretty straightforward.
