### ISSUE TITLE
setup with pi400

### ISSUE THREAD

**Issue by uriel-z** [dwhinham/mt32-pi#306]
Hello,

Trying to use the mt32-pi with a pi400 on a mister setup with no success (My understanding is that boot files for pi400 are included since v0.10.0).

I can narrow down the issue to the pi400: If I swap the pi400 for a raspberry pi 4 then it works (same mt32-pi, mister, USB cable, config file and SD card). Also feeding the system with a 5amp brick so lack of power should not be the issue.

I'm keen on helping debug the issue if I get some guidance. Any tips on how to proceed?

Thanks!

**Comment by dwhinham** [comment]
> Issues are for reproducible bug reports and feature requests.
Requests for support and "how-to" questions may be closed without notice.
