### ISSUE TITLE
💡 [FEATURE] global stereo switch option

### ISSUE THREAD

**Issue by Rixasha** [dwhinham/mt32-pi#307]
I seem to be having the left and the right channels switched for both fluidsynth and mt32 when playing midi through a McCake for some reason. This is baffling me since as far as I can tell from online threads it is not expected to happen. But it's probably not the sound card since changing to a different one didn't help, nor the cabling since sound effects still play on the correct channels, nor the software since a standalone raspberry with the same version of mt32-pi seems to play correctly. So I'm rather stumped.

If there was a global stereo switch option in mt32-pi I could at least work around it. Would it be possible to add one?

**Comment by dwhinham** [comment]
What has the vendor said about this?

**Comment by Rixasha** [comment]
I was told by the Orpheus dev that the card is built to conform to the WT spec set down by Creative, with right audio on pin 20 and left audio on pin 24, but that there was a lot of confusion on this and several manufacturers swapped them in in reference designs. The McCake dev confirmed to me that indeed it is the other way around in McCake and liked my idea of a configurable global stereo switch option in mt32-pi to work around the confusion.

**Comment by Rixasha** [comment]
Oh no, misclick.
