### ISSUE TITLE
AMIGA MIDI - Sound note continues to play after exiting game.

### ISSUE THREAD

**Issue by Higgy69** [dwhinham/mt32-pi#32]
Hi,
I mentioned this when we all were trying to sort out the hanging note issue, now that is sorted I thought I would bring this up.
I have tested with an actual AMIGA (A1200) and a MiSTER and get the same results. I tested MIDI by using some Sierra Online games (e.g. Kings Quest) which had MT-32 support and when I exit the game (I am using WHDLoad versions) a note continues to play. I have to power off the Raspberry Pi to stop the note from playing.

Thanks

**Comment by dwhinham** [comment]
Hi there,

How are you exiting these games? If you use the WHDLoad quit key, the game will be forcibly killed and will never have the chance to tell the MT-32 to turn off its notes. Make sure you're using the game's own Quit menu if you aren't already.

Can you be specific about which games and which versions are doing this?

**Comment by Higgy69** [comment]
Hi,

I think it is like you said, it is because the game is exited via WHDLoad. So it could be a tricky thing to solve, unless some signal comes through the MIDI to signify exit.
If it is impossible your end, the WHDLoad guys might be able to implement something their end. It's an option.
For games, try these links:
http://www.whdownload.com/games/K/KingsQuest5_v1.3_MT32.lha
http://www.whdownload.com/games/K/KingsQuestEnhanced_v1.1b_MT32_1436.lha
Thanks

**Comment by dwhinham** [comment]
Thanks for the links!

I think this can be solved quite easily. WHDLoad already has two mechanisms we can use:

- WHDLoad has an [`ExecuteCleanup`](http://whdload.de/docs/en/opt.html#ExecuteCleanup) option you can add to the ToolTypes of each game - this lets you run some commands after quitting on a **per-game** basis.
- It also allows you to have a script at `S:WHDLoad-Cleanup` that runs some commands after **every** game is quit.

What we need is a small tool that can send a MIDI "All Notes Off" command to the MT-32, or maybe even a full "System Reset" command. Then we just tell WHDLoad to run this tool after the game exits.

I had a look on Aminet, and whilst there are a few tools there already that can send SysEx, they are graphical tools and can't be used in automated scripts (unless anyone else knows of one I'm unaware of).

I'll try to write a small Amiga tool that can do this shortly. 😃

**Comment by dwhinham** [comment]
Download this archive and extract `killmidi` to C: on your Amiga:
[killmidi.zip](https://github.com/dwhinham/mt32-pi/files/5288894/killmidi.zip)

Note: untested on real Amiga.

## To use it for individual games:
1. Click on the WHDLoad game icon and go to the **Icons --> Information...** menu.
2. Add a new ToolType that says `ExecuteCleanup=killmidi`. It should look something like this:  
![image](https://user-images.githubusercontent.com/5890747/94373813-bf3c6980-00ff-11eb-9f0f-b42723c228f6.png)

## To use it for ALL games:
1. Open the **Workbench --> Execute Command...** menu and type `ed S:WHDLoad-Cleanup`.
2. Add a line to the bottom that simply reads `killmidi`.  
![image](https://user-images.githubusercontent.com/5890747/94373885-543f6280-0100-11eb-9a87-b5354d29eaa9.png)
3. Press ESC, then type `x` and hit Return to save.
4. Open the **Workbench --> Execute Command...** menu and type `ed S:WHDLoad.prefs`.
5. Uncomment the `ExecuteCleanup` line (delete the semicolon):  
![image](https://user-images.githubusercontent.com/5890747/94374017-29a1d980-0101-11eb-9f3a-fa0a745e56e6.png)
6. Press ESC, then type `x` and hit Return to save.

If this works for you, I'll release it as a proper tool on Aminet and so on.

**Comment by Higgy69** [comment]
Works sweet :)
I tried both options on my A1200.
Many thanks.

**Comment by dwhinham** [comment]
Great! I'll probably turn the above into a FAQ/wiki page entry soon.

Thanks for testing! 😄
