### ISSUE TITLE
Show the selected ROM version on startup

### ISSUE THREAD

**Issue by dwhinham** [dwhinham/mt32-pi#35]
As suggested by @thorr2 in another issue.

The ROM version is shown on the screen when you use a SysEx command to swap ROMs, but it would be good to show the version on startup, too.

The version strings for the ROMs are extracted from the ROM data itself, except for version 2.xx, as I don't yet have access to this ROM.

**Comment by thorr2** [comment]
Incredible new update today!  I haven't tried it yet, but thanks for all of
your efforts!

**Comment by dwhinham** [comment]
Thankyou! It's my pleasure - enjoy testing!
