### ISSUE TITLE
Compatibility Report: Innomaker Pi HiFi DAC HAT PCM5122 working

### ISSUE THREAD

**Issue by calvinmorrow** [dwhinham/mt32-pi#41]
Reporting that the Innomaker Pi HiFi DAC HAT PCM5122 is working with mt32-pi.

Used config options: ```i2c_dac_init = pcm51xx, i2c_dac_address = 4d```

Its available in the US from Amazon.  https://www.amazon.com/gp/product/B07D13QWV9/

**Comment by dwhinham** [comment]
Thanks for this! I've added it to the list.
