### ISSUE TITLE
0.8.0 not working at all on Pi 4 2GB w/Clumsy MIDI

### ISSUE THREAD

**Issue by rhester72** [dwhinham/mt32-pi#51]
I see from the Pi LED that it's trying to boot - a longish-series of flashes, a pause, a flash, a pause, a final flash, and then nothing.  No display at all on the OLED, no response to reboot SysEx over MIDI.

Replacing the kernels on the SD card with the ones from v0.7.1 restores functionality (even with the 'extra' options of the v0.8.0 config still in place).

Not sure how to debug from here.

**Comment by dwhinham** [comment]
Sorry about that! I always seem to forget something at each major release. 😅

I've just put out [v0.8.1](https://github.com/dwhinham/mt32-pi/releases/tag/v0.8.1) to take care of this.
