### ISSUE TITLE
LCD/OLED screen support

### ISSUE THREAD

**Issue by dwhinham** [dwhinham/mt32-pi#7]
One of the nice things about the desktop version of MUNT is that it simulates the LCD screen of the real device.

It would be nice to be able to hook up a cheap character LCD to the Raspberry Pi so that status information is visible along with the MT-32 SysEx messages that some games like to display on the screen.

I'm currently implementing this for a 4x20 HD44780-style screen, and will probably add support for 2 and 1-line screens too.

Demo of some work-in-progress code can be seen here:
https://www.youtube.com/watch?v=Q0_ay0dCnRU

What screens would you like to see working?

**Comment by nswaldman** [comment]
It would be very nice to see support for 128x32 OLED displays -the ubiquitous 0.91" version is very popular with Gotek and Arduino tinkerers and should be rattling around in a lot of drawers.

**Comment by SWLee0129** [comment]
I like this lcd more because it looks like MT-32.  Hope all the other functions will work just like the real device.
