### ISSUE TITLE
[REQUEST] GPIO MIDI Interface

### ISSUE THREAD

**Issue by duduke** [dwhinham/mt32-pi#9]
Can the GPIO Interface on the RPi be used as a midi device?
Something like this:

https://www.samplerbox.org/article/midiinwithrpi

Thanks.

**Comment by dwhinham** [comment]
It can! I was actually using a GPIO interface when I first started experimenting.

However, I had lots of problems with missing notes/packets, so I need to give this another go and see what was wrong.

**Comment by dwhinham** [comment]
This should be working in the latest build - I also updated the README with schematic and breadboard examples.

Thanks!

**Comment by duduke** [comment]
Dang that was fast :)
