### ISSUE TITLE
Sound output via HDMI?

### ISSUE THREAD

**Issue by rsn8887** [dwhinham/mt32-pi#96]
Why not output digital sound via HDMI, like other programs running on RPi?

HDMI audio is the only quality sound output that comes standard on RPi. The headphone jack is useless.

There are many cheap adapters that take digital sound out of HDMI and convert into other formats or output as analog.

**Comment by dwhinham** [comment]
I tried adding this, but there were huge problems with timing and latency because the audio has to go through to the GPU.

Best to use an I2S DAC or I2S SPDIF HAT.
